### ISSUE TITLE
Streamer only commands are not properly restricted

### ISSUE THREAD

**Issue by mscdex** [pixelplush/maze#1]
Commands like !end and !reset work for anyone in chat, despite being labeled "streamer only" on the game's intro graphic.

**Comment by instafluff** [comment]
They're restricted to the streamer, mods, and VIPs but actually I don't remember why I added VIPs in there. I can remove that.

**Comment by instafluff** [comment]
Fixed in 0b2862bea1f80e2624f0e7282a4d52e733da9941
